site_name: Tkinter 8.5 参考手册：一种 Python GUI
repo_url: https://github.com/Sharp-Enrich/Tkinter-8.5-reference-a-GUI-for-Python
edit_uri: edit/master/docs/
site_url: https://Tkinter-8.5-reference-a-GUI-for-Python.readthedocs.io
site_description: 描述使用Python编程语言构造图形用户界面(GUI)的Tkinter控件集，同时涵盖ttk主题控件。
site_author: Tacey Wong
copyright: ©2024 Tacey Wong
docs_dir: docs
nav:
  - 前言: index.md
  - TK章节:
    - 第1节：Python的跨平台图形用户界面构建器: 001.md
    - 第2节：一个最小的应用程序: 002.md
    - 第3节：术语定义: 003.md
    - 第4节：布局管理: 004.md
    - 第5节：标准属性(attributes): 005.md
theme:
  logo: image/tkinter.jpeg
  name: material
  language: zh
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - content.code.copy
    - content.code.select

  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/toggle-switch-off-outline
        name: 切换至暗色主题
    - scheme: slate 
      primary: black
      toggle:
        icon: material/toggle-switch
        name: 切换至浅色主题

markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.snippets:
      encoding: utf-8
  - pymdownx.highlight:
      use_pygments: true
      auto_title: true
      linenums: true
      linenums_style: pymdownx-inline
      pygments_lang_class: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - glightbox
  - search
  # - with-pdf
        #author: WHO
        #copyright: ANY TEXT
        #
        #cover: false
        #back_cover: true
        #cover_title: TITLE TEXT
        #cover_subtitle: SUBTITLE TEXT
        #custom_template_path: TEMPLATES PATH
        #
        #toc_title: TOC TITLE TEXT
        #heading_shift: false
        #toc_level: 3
        #ordered_chapter_level: 2
        #excludes_children:
        #    - 'release-notes/:upgrading'
        #    - 'release-notes/:changelog'
        #
        #exclude_pages:
        #    - 'bugs/'
        #    - 'appendix/contribute/'
        #convert_iframe:
        #    - src: IFRAME SRC
        #      img: POSTER IMAGE URL
        #      text: ALTERNATE TEXT
        #    - src: ...
        # two_columns_level: 3
        #
        #render_js: true
        #headless_chrome_path: headless-chromium
        #
        #output_path: any-place/document.pdf
        #enabled_if_env: ENABLE_PDF_EXPORT
        #
        #debug_html: true
        #show_anchors: true
        #verbose: true 
  # - pdf-export:
  #     verbose: true
  #     combined: true
  #     enabled_if_env: ENABLE_PDF_EXPORT  

extra:
  generator: false
  disqus: golang-cookbook
# https://github.com/zhaoterryy/mkdocs-pdf-export-plugin
# pip install mkdocs-pdf-export-plugin
       